export const FETCH_QUOTES = "FETCH_QUOTES";
export const FETCH_QUOTES_SUCCESS = "FETCH_QUOTES_SUCCESS";
export const FETCH_QUOTES_FAILURE = "FETCH_QUOTES_FAILURE";
export const START_API_CALL = "START_API_CALL";